<a href="https://colab.research.google.com/github/Friba-Hussa1/Handwritten_Digit_Recognition_with_CNN/blob/main/Mnist_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The problem is to classify the gray scale MNIST images into 10 classes form 0-9




*   60000 training set
*   10000 testing set



In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist


## Split data into two sets: train and test

In [2]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


## Looking into data

####images are encoded into numpy arrays and the labels are an array of digits in range if 0-9

In [6]:
train_images.shape


(60000, 28, 28)

In [7]:
len(train_labels)

60000

In [9]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [4]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## Creating the model

In [12]:
model=keras.Sequential([
    layers.Dense(512, activation="relu"),   #Dense layer is a fully connected layer
    layers.Dense(10, activation="softmax")  #this layer return an array of 10 probability score(0-9)
    ])

## Compilation step

In [13]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"]
              )

## Preparing the image data

####we’ll preprocess the data by reshaping it into the shape the model
 expects and scaling it so that all values are in the [0, 1] interval. Previously, our train
ing images were stored in an array of shape (60000, 28, 28) of type uint8 with values
 in the [0, 255] interval. We’ll transform it into a float32 array of shape (60000, 28 *
 28) with values between 0 and 1

In [14]:
train_images=train_images.reshape((60000, 28*28))
train_images=train_images.astype("float32")/255
test_images=test_images.reshape((10000, 28*28))
test_images=test_images.astype("float32")/255

##Training the mode

In [15]:
model.fit(train_images,train_labels,epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8725 - loss: 0.4412
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.9659 - loss: 0.1178
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9790 - loss: 0.0717
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9850 - loss: 0.0504
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9893 - loss: 0.0358


##Use the modle to make predicton

In [16]:
test_digits=test_images[0:10]
prediction=model.predict(test_digits)
prediction[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([4.4574983e-07, 1.4270654e-07, 1.7482389e-05, 4.4685291e-04,
       7.0668782e-10, 2.7777814e-06, 1.4355283e-11, 9.9949712e-01,
       1.6494397e-07, 3.4978868e-05], dtype=float32)

In [17]:
prediction[0].argmax()

np.int64(7)

In [18]:
prediction[0][7]

np.float32(0.9994971)

In [19]:
test_labels[0]

np.uint8(7)

##Evaluating the model on new data

In [20]:
test_loss,test_acc=model.evaluate(test_images,test_labels)
print(f"Test Accuracy:{test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9754 - loss: 0.0802
Test Accuracy:0.9779999852180481
